### ISSUE TITLE
profile image not display

### ISSUE THREAD

**Issue by sreeprakash19** [gmanojisaac/performanceBench#3]
After Login profile image  will not display....

**Comment by sreeprakash19** [comment]
after clear the history...
it will working fyn

**Comment by gmanojisaac** [comment]
It was an issue and i have tried for this fix:
    this.auth.user$.subscribe(userdata => {
      if (userdata !== undefined && userdata !== null ) {

I have to check if the userdata is undefined for the first time and null whenever we log out before we pick the image to diplay
